WIDTH, HEIGHT = 900, 500

#cores
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GREEN = (107, 142, 35)
BROWN = (139, 0, 0)

#dimencoes bordas
BORDER_DIAMETER = 30
BORDER_LEFT = pygame.Rect(0, 0, BORDER_DIAMETER, HEIGHT)
BORDER_RIGHT = pygame.Rect(WIDTH - BORDER_DIAMETER, 0, BORDER_DIAMETER, HEIGHT)
BORDER_UP = pygame.Rect(0, 0, WIDTH, BORDER_DIAMETER)
BORDER_DOWN = pygame.Rect(0, HEIGHT - BORDER_DIAMETER, WIDTH, BORDER_DIAMETER)

FPS = 30
VEL = 8

#infos cobra
COBRA_WIDTH, COBRA_HEIGHT = 30, 30
RATO_WIDTH, RATO_HEIGHT = 40, 40

#estados de jogos
INIT = 0
GAME = 1
GAMEOVER = 2
QUIT = 3